name: yardimyolda
description: "Yardım Yolda - Yol yardım ve çekici hizmeti mobil uygulaması"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Routing
  go_router: ^14.0.2
  
  # Networking
  dio: ^5.4.3+1
  
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Backend
  supabase_flutter: ^2.5.1
  
  # Maps & Location
  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  
  # Configuration
  flutter_dotenv: ^5.1.0
  
  # Utilities
  intl: ^0.19.0
  
  # Push Notifications
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11
  
  # App Icon Generation
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icon/
    - .env

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700

# Flutter Launcher Icons Configuration
# Run: flutter pub run flutter_launcher_icons
# or: dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21 # Android minimum SDK
  
  # Adaptive icon for Android 8.0+ (API 26+)
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  
  # Remove old launcher icon (optional)
  # remove_alpha_ios: true
  
  # Custom iOS icon name (optional)
  # ios_app_icon_name: "AppIcon"
  
  # Web icon (if web support is added in future)
  # web:
  #   generate: true
  #   image_path: "assets/icon/app_icon.png"
  #   background_color: "#FFFFFF"
  #   theme_color: "#2563EB"
